universe=vanilla

output=myjob.out
error=myjob.err
log=myjob-running.log

executable=../bin/Exam_JetsPlot
inputFile = root://dcgftp.usatlas.bnl.gov:1096/pnfs/usatlas.bnl.gov/LOCALGROUPDISK/rucio/data18_13TeV/03/7e/DAOD_EXOT12.14278917._000011.pool.root.1
arguments=$(inputFile)

GetEnv    = True
x509userproxy = $ENV(X509_USER_PROXY)

# this is what turns this feature on
should_transfer_files=yes
WhenToTransferOutput=on_exit

queue
