version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "latest"
  jobs:
    create_environment:
      - asdf plugin add pixi
      - asdf install pixi latest
      - asdf global pixi latest
    install:
      # assuming you have an environment called "docs"
      - pixi install
    build:
      html:
        - pixi run build
        - mkdir -p $READTHEDOCS_OUTPUT/html/
        - cp -r site/** $READTHEDOCS_OUTPUT/html/

submodules:
  include: all
  recursive: true
