[workspace]
authors = ["Giordon Stark <kratsg@gmail.com>"]
channels = ["conda-forge"]
name = "AFdocs"
platforms = ["linux-64", "linux-aarch64", "osx-64", "osx-arm64", "win-64"]
version = "0.1.0"

[tasks.build]
args = [{ "arg" = "config", "default" = "mkdocs.yml" }]
cmd = "mkdocs build --config-file {{ config }} --clean --strict"

[tasks.serve]
args = [{ "arg" = "config", "default" = "mkdocs.yml" }]
cmd = "mkdocs serve --config-file {{ config }} --dev-addr localhost:8000"

[tasks.validate]
cmd = "linkchecker --config .linkcheckerrc site"

[tasks.build-no-dir-urls]
args = [{ "arg" = "config", "default" = "mkdocs.yml" }]
cmd = "mkdocs build --config-file {{ config }} --clean --strict --no-directory-urls"

[tasks.build-check]
depends-on = ["build-no-dir-urls", "validate"]

[dependencies]
python = ">=3.14.0,<3.15"
alabaster = ">=1.0.0,<2"
mkdocs = ">=1.6.1,<2"
pillow = ">=11.3.0,<12"
sphinx_rtd_theme = ">=3.0.2,<4"
pygments = ">=2.19.2,<3"
mkdocs-table-reader-plugin = ">=3.1.0,<4"
linkchecker = ">=10.6.0,<11"
mkdocs-material = ">=9.6.21,<10"
mkdocs-git-revision-date-localized-plugin = ">=1.2.9,<2"
mkdocs-redirects = ">=1.2.1,<2"
mkdocs-glightbox = ">=0.4.0,<0.5"
pymdown-extensions = ">=10.16.1,<11"
mkdocs-include-markdown-plugin = ">=7.1.7,<8"
mkdocs-section-index = ">=0.3.10,<0.4"
mkdocs-macros-plugin = ">=1.4.0,<2"

[pypi-dependencies]
mkdocs-minify-plugin = ">=0.8.0, <0.9"
mdx-truly-sane-lists = ">=1.3, <2"
