[workspace]
authors = ["Giordon Stark <kratsg@gmail.com>"]
channels = ["conda-forge"]
name = "AFdocs"
platforms = ["linux-64", "linux-aarch64", "osx-64", "osx-arm64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.8,<3.9"
alabaster = "==0.7.12"
mkdocs = "==1.3.0"
pillow = "==8.0.1"
sphinx_rtd_theme = ">=3.0.2,<4"
pygments = "==2.14.0"
mkdocs-table-reader-plugin = "==2.0"

[pypi-dependencies]
pymdown-extensions = "==9.9.2"
mkdocs-include-markdown-plugin = "==3.2.3"
