[workspace]
authors = ["Giordon Stark <kratsg@gmail.com>"]
channels = ["conda-forge"]
name = "AFdocs"
platforms = ["linux-64", "linux-aarch64", "osx-64", "osx-arm64", "win-64"]
version = "0.1.0"

[tasks.build]
args = [{ "arg" = "config", "default" = "mkdocs.yml" }]
cmd = "mkdocs build --config-file {{ config }} --clean --strict"

[tasks.serve]
args = [{ "arg" = "config", "default" = "mkdocs.yml" }]
cmd = "mkdocs serve --config-file {{ config }} --dev-addr localhost:8000"

[tasks.validate]
cmd = "linkchecker --config .linkcheckerrc site"

[tasks.build-no-dir-urls]
args = [{ "arg" = "config", "default" = "mkdocs.yml" }]
cmd = "mkdocs build --config-file {{ config }} --clean --strict --no-directory-urls"

[tasks.build-check]
depends-on = ["build-no-dir-urls", "validate"]

[dependencies]
python = ">=3.8,<3.9"
alabaster = "==0.7.12"
mkdocs = "==1.3.0"
pillow = "==8.0.1"
sphinx_rtd_theme = ">=3.0.2,<4"
pygments = "==2.14.0"
mkdocs-table-reader-plugin = "==2.0"
linkchecker = ">=10.4.0,<11"

[pypi-dependencies]
pymdown-extensions = "==9.9.2"
mkdocs-include-markdown-plugin = "==3.2.3"
